### ISSUE TITLE
Update file returns null error with local emulator

### ISSUE THREAD

**Issue by Lihan-Chen** [Azure/azure-cosmos-dotnet-v2#678] opened 2019-02-10 08:31 UTC
Update file returns null error with local emulator

I am having the error of return null for uploading json file that works fine on Azure.  It reports null and holds the process for a long time and eventually causes the blue screen with a stop code: code page in a non-page zone.

**Comment by spettifer** [comment] 2019-04-16 13:06
I can reproduce this. Attempting upload valid JSON with a handful of records causes the following:

![image](https://user-images.githubusercontent.com/8904474/56211654-3c7d3700-6050-11e9-829c-923fdd0a37d2.png)

![image](https://user-images.githubusercontent.com/8904474/56211676-4737cc00-6050-11e9-9731-c6e996eca174.png)


The spinner in the messages pane keeps going.

Emulator version 2.2.1.0

Sample of the JSON file:

```
[
	{			
		"id": "1d3e9c8b-d173-4105-9c1a-d76d028fc7c3",
		"bookingref": "BK000004",
		"bookingdate": "1549394520",
		"contact": {
			"forename": "Thor",
			"surname": "Bjornsson",
			"profileref": "prf003"
		}
	},
	{		
		"id": "0d1d11ea-e6ad-4310-b002-e332ffbdc1b6",
		"bookingref": "BK000005",
		"bookingdate": "1553791500",
		"contact": {
			"forename": "Eddie",
			"surname": "Hall",
			"profileref": "pf001"
		}
	},
	{
		"id": "1f7e545f-c1ef-4fda-a26c-abbd3cc227a2",
		"bookingref": "BK000006",
		"bookingdate": "1540794600",
		"contact": {
			"forename": "Magnus",
			"surname": "Midtbo",
			"profileref": "pf002"
		}
	},
	{
		"id": "364be7e9-b882-4890-8e8c-82b7b828c176",
		"bookingref": "BK000007",
		"bookingdate": "1554891000",
		"contact": {
			"forename": "Jon",
			"surname": "Call",
			"profileref": "pro001-1"
		}
	},
	{
		"id": "6ab0c130-9c27-4820-a71e-fbbbce7015b7",
		"bookingref": "BK000008",
		"bookingdate": "1547421780",
		"contact": {
			"forename": "Bouldering",
			"surname": "Bobat",
			"profileref": "pro002-1"
		}
	}
]
```

**Comment by yuvarajagna** [comment] 2019-08-09 05:22
any fix for this issue?

**Comment by shearer3000** [comment] 2020-06-16 23:31
any ideas on this? thanks

**Comment by j82w** [comment] 2020-06-17 14:48
Please upgrade the emulator to the latest version. It should be fixed in version 2.11.1

**Comment by shearer3000** [comment] 2020-06-17 20:01
thanks - that worked :)

**Closed** 2020-06-17 22:57 UTC

**Comment by shearer3000** [comment] 2020-06-17 23:49
hey @j82w its been a good 12+ months since i worked with the emulator, but refreshing myself on the azure cosmos "non production" development/testing free pricing tier, i take that to mean Microsoft are now steering people away from the emulator to use Azure services directly instead? that would make complete sense to me anyway
