### ISSUE TITLE
Contains a single character in a property returns inconsistent results from CosmosDB

### ISSUE THREAD

**Issue by kkostov5** [Azure/azure-cosmos-dotnet-v2#582] opened 2018-08-31 10:23 UTC
I have just run into an issue when looking up documents in CosmosDB by checking if a property of the document contains a specific searched value. What I want to achieve was to show a list of results to the user on the user entry of each character of the desired searched value - so each user input would fire a request to the database with the changed searched value. So when trying to lookup up I would convert both the field and the searched value in either lower or upper case. The problem occurs when the searched term contains only one character as it would occasionally give results that do not contain that character in the corresponding property.

Here is an example: 

The example data that the CosmosDB table holds:
```
{
    "entityType": 2,
    "org_id": "some guid",
    "identifier": "serialnumber1" 
} 
```
(I have stored documents with serialnumber1 to serialnumber12 just for testing purposes)

Linq query:
```
object => object .EntityType == 2 && object.OrgId == "some guid" &&
                      device.Identifier.ToUpper().Contains(identifier.ToUpper())
```

Also tried using SqlQuerySpec class as well to build a query to the database:
```
new SqlQuerySpec {
       QueryText = "SELECT TOP 10 * FROM Table t WHERE (t.entityType = @entityType AND t.org_id = @orgId AND CONTAINS(LOWER(t.identifier), @identifier))",
       Parameters = new SqlParameterCollection
        {    new SqlParameter("@entityType", 2),
             new SqlParameter("@orgId", orgId),
             new SqlParameter("@identifier", identifier.ToLower())
       }
}
```
The searched term that was used was a single character for example - "t" or "d" or "f" - and it would cause the occasional misbehavior. Pretty much every one in 10 tries would return a random response that I was not expecting as "t"/"d"/"f" are not contained within the string "serialnumber" that I had stored in the database.

If the searched term is longer than a single character, it seems to be working fine.

Thus, I was wondering what could be causing this behavior?

**Comment by jackbond** [comment] 2018-09-05 15:21
It took me under five minutes to write a unit test that confirms that this is in fact A MASSIVE BUG. Normally this might go weeks without a response, but I'm guessing that they'll be responding shortly.

**Comment by jackbond** [comment] 2018-09-06 03:49
ActivityId: 71e235c6-8ac8-400e-8e72-0c57c4c01d1a

With code that looked like this...

```
            var query = _DocumentClientRO
                        .CreateDocumentQuery<T>(CollectionUri)
                        .Where(predicate)
                        .Take(maxItemCount)
                        .AsDocumentQuery<T>();
```

I did a ToString() on query and it looked like this...

`{"query":"SELECT TOP 1 * FROM root WHERE ((root[\"docType\"] = 4) AND CONTAINS(UPPER(root[\"gameName\"]), \"J\")) "}`

Ok, I've now recreated this problem via the azure portal. I had to run the query multiple times, and most of the time I'd get back no results, but occasionally I'd get a result.

![upperissue](https://user-images.githubusercontent.com/2799232/45133935-d3922000-b14c-11e8-8c4d-0b64d98e49ed.png)

**Comment by kirillg** [comment] 2018-09-06 19:39
Folks, while someone looks into this deeper, could you check if HasMoreResults == true? Sometimes we return empty pages even though the query has more results. In this case lower or upper may lead to poor query performance leading to more pages. You can further troubleshoot query performance by looking at the query metrics documented here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query-metrics . You can see these in the portal as well (currently using special URL: https://portal.azure.com/?feature.dataexplorerquerymetrics=true )

**Comment by jackbond** [comment] 2018-09-07 00:38
@kirillg I've got feature.dataexplorerquerymetrics=true in the querystring but I'm not seeing any additional information. My query also restricts the results to about 20 documents, i.e. c["docType"] = 4, and returns almost instantly, so I don't believe there are more results.

I'm also seeing the same behavior with LOWER in the query...

> WHERE ((c["docType"] = 4) AND CONTAINS(LOWER(c.gameName), "J"))

It seems to be some weird incompatibility between the CONTAINS and UPPER/LOWER functions. I haven't been able to reproduce the problem with STARTSWITH or ENDSWITH.

**Comment by kirillg** [comment] 2018-09-07 05:48
thanks Jack. Service some times will send an empty page with continuation token if the time limit or RU budget allocated to the current execution episode is exhausted. If the filter expression leads to poor performance (e.g. scan), this can happen even if you're not asking for lots of results. Try clicking "Load More" at the bottom in your current repro to see if there are more results. To see the query metrics, you need to run this query in a query tab which you get by clicking "New Query". once you have the results, click on Query Results tab (see image below)
![image](https://user-images.githubusercontent.com/1079707/45200524-1542c980-b226-11e8-9390-f13d318a20d4.png)

**Comment by jackbond** [comment] 2018-09-07 06:05
The results were four game documents which didn't have a "J" in their names. 

Activity Id: 15f216e9-9e87-401d-b011-d537a4eb8d74

![queryinformation](https://user-images.githubusercontent.com/2799232/45201151-f09c2100-b228-11e8-8983-c280b1ad884c.png)

**Comment by kirillg** [comment] 2018-09-10 06:28
@kkostov5 @jackbond this is confirmed to be a regression in our backend. Fix is partially deployed and will get fully deployed  worldwide over the course of the next two weeks.

**Comment by khdang** [comment] 2019-01-25 05:30
Closing this issue as the fix has been deployed.

**Closed by khdang** 2019-01-25 05:30 UTC
Labels: bug
