### ISSUE TITLE
FetchNextSet does not honor custom serializer settings

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v2#673] opened 2019-02-08 02:09 UTC
## Describe the bug
After assigning custom serializer settings, `FetchNextSet` does not use them.

## To Reproduce

Here is a complete repro as a LINQPad C# program. Notice that reading the item with `ReadItemAsync` works just fine, but not with `FetchNextSetAsync`. The packages this script depends on are:

* `Microsoft.Azure.Cosmos` version `3.0.0.1-preview`
* `NodaTime.Serialization.JsonNet` version `2.1.0`

```C#
async Task Main()
{
    var connectionString = <<connection string here>>;
    var cosmosConfiguration = new MyCosmosConfiguration(connectionString);
    var cosmosClient = new CosmosClient(cosmosConfiguration);

    var databaseResult = await cosmosClient.Databases.CreateDatabaseIfNotExistsAsync("repro");
    var database = databaseResult.Database;
    var containerResult = await database.Containers.CreateContainerIfNotExistsAsync("items", "/id");
    var container = containerResult.Container;

    var itemId = Guid.NewGuid().ToString();
    
    var item = new ItemEntity
    {
        Id = itemId,
        Timestamp = SystemClock.Instance.GetCurrentInstant().InUtc()
    };
    
    await container.Items.UpsertItemAsync(itemId, item);

    // This works - the item is retrieved and the timestamp is set correctly
    var readItemResult = await container.Items.ReadItemAsync<ItemEntity>(itemId, itemId);
    var readItem = readItemResult.Resource;
    readItem.Dump("Retrieved with ReadItemAsync");

    // This does not because FetchNextSetAsync seemingly does not use our custom serializer settings
    var sql = new CosmosSqlQueryDefinition("SELECT * FROM i");
    var query = container.Items.CreateItemQuery<ItemEntity>(sql, 2);

    while (query.HasMoreResults)
    {
        var currentResultSet = await query.FetchNextSetAsync();

        foreach (var result in currentResultSet)
        {
            result.Dump("Result from FetchNextSet");
        }
    }
}

public sealed class ItemEntity
{
    [JsonProperty("id")]
    public string Id { get; set; }
    
    [JsonProperty("timestamp")]
    public ZonedDateTime Timestamp { get; set; }
}

public sealed class MyCosmosConfiguration : CosmosConfiguration
{
    public MyCosmosConfiguration(string connectionString)
        : base(connectionString)
    {
        this.UseCustomJsonSerializer(JsonNetCosmosJsonSerializer.Instance);
    }

    private sealed class JsonNetCosmosJsonSerializer : CosmosJsonSerializer
    {
        public static readonly JsonNetCosmosJsonSerializer Instance = new JsonNetCosmosJsonSerializer();
        private static readonly JsonSerializer serializer = JsonSerializer.Create(MyJsonSerializerSettings.Instance);

        private JsonNetCosmosJsonSerializer()
        {
        }

        public override T FromStream<T>(Stream stream)
        {
            using (stream)
            {
                if (typeof(Stream).IsAssignableFrom(typeof(T)))
                {
                    return (T)(object)stream;
                }

                using (var streamReader = new StreamReader(stream))
                using (var jsonTextReader = new JsonTextReader(streamReader))
                {
                    return serializer.Deserialize<T>(jsonTextReader);
                }
            }
        }

        public override Stream ToStream<T>(T input)
        {
            var streamPayload = new MemoryStream();

            using (var streamWriter = new StreamWriter(streamPayload, encoding: Encoding.Default, bufferSize: 1024, leaveOpen: true))
            using (var writer = new JsonTextWriter(streamWriter))
            {
                writer.Formatting = Newtonsoft.Json.Formatting.None;
                serializer.Serialize(writer, input);
                writer.Flush();
                streamWriter.Flush();
            }

            streamPayload.Position = 0;
            return streamPayload;
        }
    }
}

public sealed class MyJsonSerializerSettings : JsonSerializerSettings
{
    public static readonly MyJsonSerializerSettings Instance = new MyJsonSerializerSettings();

    private MyJsonSerializerSettings()
    {
        this.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
    }
}
```

## Expected behavior
The deserialization should work regardless of how items are retrieved via the container.

## Actual behavior

```

Error converting value "2019-02-08T01:57:20.1701824Z UTC" to type 'NodaTime.ZonedDateTime'. Path 'timestamp', line 1, position 127. | Error converting value "2019-02-08T01:57:20.1701824Z UTC" to type 'NodaTime.ZonedDateTime'. Path 'timestamp', line 1, position 127.
-- | --
Error converting value "2019-02-08T01:57:20.1701824Z UTC" to type 'NodaTime.ZonedDateTime'. Path 'timestamp', line 1, position 127.
 
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Microsoft.Azure.Cosmos.Internal.QueryResult.Convert(Type type)
at Microsoft.Azure.Cosmos.Internal.QueryResult.AsType[T]()
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at Microsoft.Azure.Cosmos.FeedResponseBinder.Convert[T](FeedResponse`1 dynamicFeed)
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at Microsoft.Azure.Cosmos.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.CosmosItems.<NextResultSetAsync>d__29`1.MoveNext() | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Microsoft.Azure.Cosmos.Internal.QueryResult.Convert(Type type)
at Microsoft.Azure.Cosmos.Internal.QueryResult.AsType[T]()
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at Microsoft.Azure.Cosmos.FeedResponseBinder.Convert[T](FeedResponse`1 dynamicFeed)
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at Microsoft.Azure.Cosmos.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.CosmosItems.<NextResultSetAsync>d__29`1.MoveNext()
```

## Environment summary
SDK Version: 3.0.0.1-preview
OS Version: Windows 10

## Additional context
Reproduces against Cosmos emulator as well.

**Comment by ealsur** [comment] 2019-02-08 19:15
@kentcb This is the wrong repository. Issues with V3 are tracked here https://github.com/Azure/azure-cosmos-dotnet-v3/issues/.

Closing as it's a duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/19

**Closed by ealsur** 2019-02-08 19:15 UTC
